
CREATE TABLE ECRM_TEMPLATES
(
  
  APPLICATION_NAME               VARCHAR2(20 BYTE),
  CATEGORY                       VARCHAR2(25 BYTE),
  CONTENT_TYPE                   VARCHAR2(10 BYTE) NOT NULL,
  DISP_TEMPLATE_NAME             VARCHAR2(100 BYTE),
  IS_DYNAMIC_TEMPLATE            VARCHAR2(1 BYTE),
  LANGUAGE                       VARCHAR2(2 BYTE),
  LOB                            VARCHAR2(5 BYTE),
  PROD_CATEGORY                  NUMBER(3),
  SEQ_ID                         NUMBER         NOT NULL,
  STATUS                         VARCHAR2(1 BYTE),
  SUBJECT                        VARCHAR2(4000 BYTE),
  TEMPLATE_ID                    NUMBER,
  TRANSACTION_TYPE               VARCHAR2(50 BYTE)
    )

CREATE INDEX CR_DT_IDX ON ECRM_TEMPLATES
(CREATED_DATE)
LOGGING
TABLESPACE EOD_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX ETEMP_NM_IDX ON ECRM_TEMPLATES
(NAME)
LOGGING
TABLESPACE PNPDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX MAPPED_TEMPLATE_IDX ON ECRM_TEMPLATES
(MAPPED_TEMPLATE_ID)
LOGGING
TABLESPACE PNPINDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

CREATE UNIQUE INDEX ONDEMAND_SIMPLE_PK ON ECRM_TEMPLATES
(SEQ_ID)
LOGGING
TABLESPACE EOD_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX TEMPLATE_ID_VER_INDX ON ECRM_TEMPLATES
(TEMPLATE_ID, VERSION_NO)
LOGGING
TABLESPACE EOD_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX UK_TEMPNAME_VERSION ON ECRM_TEMPLATES
(NAME, VERSION_NO)
LOGGING
TABLESPACE EOD_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE SYNONYM PNP_USER.ECRM_TEMPLATES FOR ECRM_TEMPLATES;


CREATE OR REPLACE PUBLIC SYNONYM ECRM_TEMPLATES FOR ECRM_TEMPLATES;


ALTER TABLE ECRM_TEMPLATES ADD (
  CONSTRAINT ONDEMAND_SIMPLE_PK
  PRIMARY KEY
  (SEQ_ID)
  USING INDEX ONDEMAND_SIMPLE_PK
  ENABLE VALIDATE,
  CONSTRAINT TEMP_ID_VERSION_UK
  UNIQUE (TEMPLATE_ID, VERSION_NO)
  USING INDEX TEMPLATE_ID_VER_INDX
  ENABLE VALIDATE,
  CONSTRAINT UK_TEMPNAME_VERSION
  UNIQUE (NAME, VERSION_NO)
  USING INDEX UK_TEMPNAME_VERSION
  ENABLE VALIDATE);

ALTER TABLE ECRM_TEMPLATES ADD (
  CONSTRAINT PROD_CATEGORY_FK 
  FOREIGN KEY (PROD_CATEGORY) 
  REFERENCES PRODUCT_CATEGORY_REF (CODE)
  ENABLE VALIDATE,
  CONSTRAINT TEMP_CAT_FK 
  FOREIGN KEY (CATEGORY) 
  REFERENCES ECRM_TEMPLATE_CATEGORY (CATEGORY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT TEMP_ROLE_FK 
  FOREIGN KEY (CREATED_ROLE) 
  REFERENCES VZ_ECRM_ROLE (ROLE_ID)
  ENABLE VALIDATE);

