
CREATE TABLE PNP_ADMIN.EMAIL_STATUS_REF
(
  DESCRIPTION         VARCHAR2(500 CHAR)        NOT NULL,
    OVERALL_STATUS      VARCHAR2(20 CHAR)         NOT NULL,
  STATUS_ID           NUMBER,
  STATUS_TEXT         VARCHAR2(100 CHAR)        NOT NULL
)
TABLESPACE PNPDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX PNP_ADMIN.EMAIL_STATUS_REF_PK ON PNP_ADMIN.EMAIL_STATUS_REF
(STATUS_ID)
LOGGING
TABLESPACE PNPINDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE PUBLIC SYNONYM EMAIL_STATUS_REF FOR PNP_ADMIN.EMAIL_STATUS_REF;


ALTER TABLE PNP_ADMIN.EMAIL_STATUS_REF ADD (
  CONSTRAINT EMAIL_STATUS_REF_PK
  PRIMARY KEY
  (STATUS_ID)
  USING INDEX PNP_ADMIN.EMAIL_STATUS_REF_PK
  ENABLE VALIDATE);

